/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type Item = {
  _id: string;
  _type: "item";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: I18nString;
  description?: I18nText;
  category?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "category";
  };
  basePrice?: number;
  mainImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  gallery?: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
  variants?: Array<{
    _key: string;
  } & Variant>;
  allergens?: Array<string>;
  tags?: Array<string>;
  order?: number;
  isAvailable?: boolean;
};

export type Variant = {
  _type: "variant";
  label?: I18nString;
  price?: number;
  order?: number;
  isDefault?: boolean;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: I18nString;
  slug?: Slug;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  kind?: "food" | "drink";
  order?: number;
  isActive?: boolean;
};

export type I18nText = {
  _type: "i18nText";
  it?: string;
  en?: string;
};

export type I18nString = {
  _type: "i18nString";
  it?: string;
  en?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type AllSanitySchemaTypes = Item | Variant | Category | I18nText | I18nString | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageHotspot | SanityImageCrop | SanityFileAsset | SanityImageAsset | SanityImageMetadata | Geopoint | Slug | SanityAssetSourceData;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ../src/lib/cms/client.ts
// Variable: menuByKindQuery
// Query: *[_type == "category" && kind == $kind && isActive == true]  | order(order asc) {    _id,    title,    kind,    order,    isActive,    image {      "url": asset->url,      alt    },    "items": *[      _type == "item" &&      isAvailable == true &&      references(^._id)    ] | order(order asc) {      _id,      name,      description,      basePrice,      mainImage {        "url": asset->url,        alt      },      gallery[] {        "url": asset->url,        alt      },      variants,      allergens,      tags,      order,      isAvailable    }  }
export type MenuByKindQueryResult = Array<{
  _id: string;
  title: I18nString | null;
  kind: "drink" | "food" | null;
  order: number | null;
  isActive: boolean | null;
  image: {
    url: string | null;
    alt: string | null;
  } | null;
  items: Array<{
    _id: string;
    name: I18nString | null;
    description: I18nText | null;
    basePrice: number | null;
    mainImage: {
      url: string | null;
      alt: string | null;
    } | null;
    gallery: Array<{
      url: string | null;
      alt: string | null;
    }> | null;
    variants: Array<{
      _key: string;
    } & Variant> | null;
    allergens: Array<string> | null;
    tags: Array<string> | null;
    order: number | null;
    isAvailable: boolean | null;
  }>;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "\n*[_type == \"category\" && kind == $kind && isActive == true]\n  | order(order asc) {\n    _id,\n    title,\n    kind,\n    order,\n    isActive,\n    image {\n      \"url\": asset->url,\n      alt\n    },\n    \"items\": *[\n      _type == \"item\" &&\n      isAvailable == true &&\n      references(^._id)\n    ] | order(order asc) {\n      _id,\n      name,\n      description,\n      basePrice,\n      mainImage {\n        \"url\": asset->url,\n        alt\n      },\n      gallery[] {\n        \"url\": asset->url,\n        alt\n      },\n      variants,\n      allergens,\n      tags,\n      order,\n      isAvailable\n    }\n  }\n": MenuByKindQueryResult;
  }
}
